config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resources :resumes

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
# frozen_string_literal: true

class Resume < ApplicationRecord
  validates :name, presence: true
  validates :contact, presence: true

  # BEGIN
  has_many :educations, inverse_of: :resume, class_name: 'ResumeEducation', dependent: :destroy
  has_many :works, inverse_of: :resume, class_name: 'ResumeWork', dependent: :destroy

  accepts_nested_attributes_for :educations, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :works, reject_if: :all_blank, allow_destroy: true
  # END
end

app/models/resume_education.rb
# frozen_string_literal: true

class ResumeEducation < ApplicationRecord
  validates :institution, presence: true
  validates :faculty, presence: true
  validates :begin_date, presence: true

  # BEGIN
  belongs_to :resume, inverse_of: :educations
  # END
end

app/models/resume_work.rb
# frozen_string_literal: true

class ResumeWork < ApplicationRecord
  validates :company, presence: true
  validates :begin_date, presence: true

  # BEGIN
  belongs_to :resume, inverse_of: :works
  # END
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/resumes_controller.rb
# frozen_string_literal: true

class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
  end

  def show
    @resume = resource_resume

    @resume_educations = @resume.educations
    @resume_works = @resume.works
  end

  def new
    @resume = Resume.new
  end

  def edit
    @resume = resource_resume
  end

  def create
    @resume = Resume.new(resume_params)

    if @resume.save
      redirect_to @resume, notice: 'Resume was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if resource_resume.update(resume_params)
      redirect_to resource_resume, notice: 'Resume was successfully updated.'
    else
      @resume = resource_resume

      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    resource_resume.destroy

    redirect_to resumes_url, notice: 'Resume was successfully destroyed.'
  end

  private

  def resource_resume
    @resource_resume ||= Resume.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def resume_params
    params.require(:resume).permit(
      :name,
      :contact,
      :github_url,
      :summary,
      educations_attributes: %i[
        id
        institution
        faculty
        begin_date
        end_date
      ],
      works_attributes: %i[
        id
        company
        begin_date
        end_date
      ]
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/views/home/index.html.slim
= content_for :title do
  = 'Home#index'

app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title Nested forms
    == csrf_meta_tags
    == csp_meta_tag
    meta name="keywords" content="template language"
    meta name="author" content='author'
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    == stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    == javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body.d-flex.flex-column.h-100

    = render 'layouts/shared/nav'

    = render 'layouts/shared/flash'

    main
      .mt-4.mb-5.pb-5
        .container
          .p-4.align-items-center.border.shadow.bg-white.rounded-3
            .row
              .p-3.p-lg-5.pt-lg-0
                .mb-4
                  h2 = yield :title
                  hr

                == yield

    footer.bg-dark.text-light.mt-auto
      .container-xl
        .row.py-2
          = "© Hexlet ltd, #{Time.zone.today.year}"

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |_type, msg|
      .alert.alert-info
        = msg

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light
      a.navbar-brand.me-md-4(href='/')
        = image_tag 'logo.png', width: 30, alt: 'Hexlet logo'

      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav
          li.nav-item.me-2
            = link_to 'Home', root_path, class: 'nav-link text-dark'
          li.nav-item.me-2
            = link_to 'Resumes', resumes_path, class: 'nav-link text-dark'

app/views/resumes/_education_fields.html.slim
.nested-fields
  = f.input :institution
  = f.input :faculty
  .row
    .col
      = f.input :begin_date, as: :date, discard_day: true, include_blank: true, start_year: 1970
    .col
      = f.input :end_date, as: :date, discard_day: true, include_blank: true, start_year: 1970, wrapper_html: { class: 'col-sm' }
  .mb-3
    = link_to_remove_association t('.remove_education'), f

app/views/resumes/_form.html.slim
= simple_form_for(@resume) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :name
  = f.input :contact
  = f.input :github_url
  = f.input :summary, input_html: { rows: 10 }

  hr

  h3.my-4 = 'Education'
  #education
    / BEGIN
    = f.simple_fields_for :educations do |education|
      = render 'education_fields', f: education
    .links.my-1
      = link_to_add_association 'Add education item', f, :educations
    / END

  h3.my-4 = 'Work'
  #work
    = f.simple_fields_for :works do |work|
      = render 'work_fields', f: work
    .links.my-1
      = link_to_add_association 'Add work item', f, :works

  = f.button :submit, class: 'btn btn-success mt-4 btn-block'

app/views/resumes/_work_fields.html.slim
  .nested-fields
    = f.input :company

    .row
      .col
        = f.input :begin_date, as: :date, discard_day: true, include_blank: true, start_year: 1970
      .col
        = f.input :end_date, as: :date, discard_day: true, include_blank: true, start_year: 1970, wrapper_html: { class: 'col-sm' }
    .mb-3
      = link_to_remove_association t('.remove_work'), f

app/views/resumes/edit.html.slim
= content_for :title do
  = 'Editing resume'

== render 'form'

hr

.d-flex
  = link_to 'Show', @resume, class: 'btn btn-outline-primary me-2'
  = link_to 'Back', :back, class: 'btn btn-outline-primary'

app/views/resumes/index.html.slim
= content_for :title do
  = 'Resumes'

table.table.table-striped.table-hover.mb-5
  thead
    tr
      th{ scope: :col } #
      th{ scope: :col } Name
      th{ scope: :col } Contact
      th

  tbody
    - @resumes.each_with_index do |resume, i|
      tr
        th{ scope: :col } = i + 1
        td = resume.name
        td = resume.contact
        td.d-flex
          .me-4 = link_to 'Show', resume
          .me-4 = link_to 'Edit', edit_resume_path(resume)
          = link_to 'Destroy', resume, data: { confirm: 'Are you sure?' }, method: :delete

= link_to 'New Resume', new_resume_path, class: 'btn btn-primary'

app/views/resumes/new.html.slim
= content_for :title do
  = 'New Resume'

== render 'form'

hr

= link_to 'Back', :back, class: 'btn btn-outline-primary'

app/views/resumes/show.html.slim
= content_for :title do
  = @resume.name

.d-flex
  h4.my-4.me-3 = 'Basic'
  hr.my-auto.w-100

.row.mb-3
  .col-sm-3
    b = 'Contact'
  .col-sm-9
    == @resume.contact

.row.mb-3
  .col-sm-3
    b = 'Githab'
  .col-sm-9
    == @resume.github_url

.row.mb-3
  .col-sm-3
    b = 'Summary'
  .col-sm-9
    == @resume.summary

- if @resume_educations.any?
  .d-flex
    h4.my-4.me-3 = 'Education'
    hr.my-auto.w-100

- @resume_educations.each do |education|
  .mb-4
    = education.institution
    .small.text-muted.mt-1.mb-2
      = l education.begin_date, format: :discard_day
      - if education.end_date
        | &nbsp;-&nbsp;
        = l education.end_date, format: :discard_day

- if @resume_works.any?
  .d-flex
    h4.my-4.me-3 = 'Work'
    hr.my-auto.w-100

  - @resume_works.each do |work|
    .mb-4
      b = work.company
      .small.text-muted.mt-1.mb-2
        = l work.begin_date, format: :discard_day
          | &nbsp;-&nbsp;
          = l work.end_date, format: :discard_day

.d-flex
  = link_to 'Edit', edit_resume_path(@resume), class: 'btn btn-outline-primary me-2'
  = link_to 'Back', :back, class: 'btn btn-outline-primary'